version: '3'

services:
  mongo:
    image: mongo
    container_name: {project}-mongo
    ports:
     - 27017:27017
    restart: always
    volumes:
     - mongodb-data:/data/db

{dockerservices}
volumes:
  mongodb-data: