[Service]
BootTimeout = 30000
Host = '0.0.0.0'
Port = {portnumber}
Protocol = 'http'
StartupMsg = 'This is the {servicename} Microservice'
Timeout = 5000

[Databases]
Host = '{project}-mongo'
Name = '{servicename}'
Username = ''
Password = ''
Port = 27017
Timeout = 5000
Type = 'mongodb'

[Logging]
LogLevel = 'TRACE'
EnableRemote = false
File = './logs/test.log'

[Startup]
Duration = 30
Interval = 1
