[Service]
BootTimeout = 30000
Host = '0.0.0.0'
Port = {portnumber}
Protocol = 'http'
StartupMsg = 'This is the {servicename} microservice'
Timeout = 5000

[Databases]
Host = '{project}-mongo'
Name = '{servicename}'
Username = ''
Password = ''
Port = 27017
Timeout = 5000
Type = 'mongodb'

[Logging]
LogLevel = 'TRACE' # TRACE, DEBUG, INFO, WARN, ERROR
File = '' # Enter log file path if you want to save your logs (./logs/test.log)

[Startup]
Duration = 30
Interval = 1
